### PR TITLE
Interactive buttons

### PR DESCRIPTION
**Pull request by fiddyhamma**
I made changes to the buttons and corrected a typo in the README

### CODE REVIEW

**Comment by proffapt** [comment]
Can you share an ss for the current looks?

**Comment by fiddyhamma** [comment]
Screenshot (218)

**Comment by proffapt** [comment]
Mhmm, they look too old designs; can you implement something of this age??

**Comment by fiddyhamma** [comment]
Okay, working on it

**Review by proffapt — APPROVED** [review]
Everything LGTM.
But you also need to add multiple dimensions of the logo for various places the extension is seen.

**Review by proffapt — APPROVED** [review]
LGTM.

**Pull request merged**
