### PR TITLE
Porting to Manifestv3

### LINKED ISSUE #22: Update Chrome extension to Manifest v3
Manifest v2 will not be supported in the near future, shifting to v3 will need to modify the codebase to huge extent.

Work is being done in #24

### PR DESCRIPTION
**Pull request by harshit-jain52**
### What?

Modified `manifest.json` to v3

Closes #22 

### ToDo

- [x] update [manifest.json](https://github.com/proffapt/fERP/blob/main/extension-src/chrome/manifest.json)
- [x] update [main.js](https://github.com/proffapt/fERP/blob/main/extension-src/chrome/js/main.js)
- [ ] update [feedback.js](https://github.com/proffapt/fERP/blob/main/extension-src/chrome/js/feedback.js)

### CODE REVIEW

**Comment by harshit-jain52** [comment]
I have implemented the changes that I could find [here](https://developer.chrome.com/docs/extensions/migrating/). Can we check if they're working or not?

**Comment by proffapt** [comment]
doesn't `feedback.js` require changes?

**Comment by harshit-jain52** [comment]
> doesn't `feedback.js` require changes?

None that I could find. I'll search again.

**Comment by proffapt** [comment]
Then ig wait for the feedback form to open or create something to test for it, I had the feedback form downloaded but my device was repaired so had to format ssd :/

**Comment by harshit-jain52** [comment]
How exactly to test the software on a particular branch?. I mean, this PR hasn't been merged, but i wanna test this. Sorry I don't have any JS experience.

**Comment by proffapt** [comment]
You have the code in your local right?
Follow the steps in the readme to install them manually.. for firefox you will have to zip the extension using `web-ext build`.

You may search for "How to install extension manually on chrom/firefox"

**Comment by proffapt** [comment]
https://github.com/proffapt/fERP?tab=readme-ov-file#firefox -> Manual part
https://github.com/proffapt/fERP?tab=readme-ov-file#chromium-based-browsers

**Comment by harshit-jain52** [comment]
Screenshot from 2023-11-10 16-58-35
Screenshot from 2023-11-10 17-00-24

**Comment by harshit-jain52** [comment]
> Screenshot from 2023-11-10 16-58-35 Screenshot from 2023-11-10 17-00-24

image
same error even after adding target

**Comment by harshit-jain52** [comment]
image
added `tabId` , still error

**Comment by harshit-jain52** [comment]
image

It seems the registration of event listeners in `feedback,js` has to be changed. I'm not sure how.

**Comment by proffapt** [comment]
Closing this, since I will be working on it rn, thanks for the efforts <3

**Pull request closed without merging**
