### PR TITLE
change in user interface (UI)

### PR DESCRIPTION
**Pull request by shivambisen**
# Description

Upon evaluating the user interface of the existing extension, it became apparent that its design was notably antiquated, reminiscent of outdated government websites.

Fixes # (issue)

Implemented a palette of cool colors to evoke a sense of comfort for users, while also striving to align with modern design trends.

Screenshot 2023-12-22 233849

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by proffapt** [comment]
> notably antiquated, reminiscent of outdated government websites.

Umm, what?

Also, would encourage to work on existing issues here, the UI/UX is not something urgent.

**Comment by shivambisen** [comment]
Sure is there any features or issue in this repository you want me to work on ?

**Comment by proffapt** [comment]
yes there are, checkout open issues regarding the following two in order of priority:
- porting to manifestv3 properly for chrome
- solve captcha

**Comment by proffapt** [comment]
With this, I am closing the PR

**Pull request closed without merging**
